// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiXWnHwrdTHlyVEY7LeffXxrD9zO1q3BI',
    appId: '1:872582145499:web:82a9f715702145d56773fe',
    messagingSenderId: '872582145499',
    projectId: 'ipldata-f1614',
    authDomain: 'ipldata-f1614.firebaseapp.com',
    storageBucket: 'ipldata-f1614.appspot.com',
    measurementId: 'G-S375230TKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7aELsLYlxsYhQXD_0OVZ2ZgZwre0HrxY',
    appId: '1:872582145499:android:c668f23cf7ae32966773fe',
    messagingSenderId: '872582145499',
    projectId: 'ipldata-f1614',
    storageBucket: 'ipldata-f1614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv0zxHjqL3p1IzfjZcgsk7cLmR4Ty5y4I',
    appId: '1:872582145499:ios:ae74511d3cf0345c6773fe',
    messagingSenderId: '872582145499',
    projectId: 'ipldata-f1614',
    storageBucket: 'ipldata-f1614.appspot.com',
    iosBundleId: 'com.example.blogAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv0zxHjqL3p1IzfjZcgsk7cLmR4Ty5y4I',
    appId: '1:872582145499:ios:ae74511d3cf0345c6773fe',
    messagingSenderId: '872582145499',
    projectId: 'ipldata-f1614',
    storageBucket: 'ipldata-f1614.appspot.com',
    iosBundleId: 'com.example.blogAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiXWnHwrdTHlyVEY7LeffXxrD9zO1q3BI',
    appId: '1:872582145499:web:07ec76e328635a146773fe',
    messagingSenderId: '872582145499',
    projectId: 'ipldata-f1614',
    authDomain: 'ipldata-f1614.firebaseapp.com',
    storageBucket: 'ipldata-f1614.appspot.com',
    measurementId: 'G-QRB05NEFY7',
  );
}
